# Generated by Django 5.1.6 on 2025-02-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('otc', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(blank=True, max_length=255, null=True)),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('level_winter', models.CharField(blank=True, max_length=10, null=True)),
                ('level_summer', models.CharField(blank=True, max_length=10, null=True)),
                ('level_autumn', models.CharField(blank=True, max_length=10, null=True)),
                ('level_spring', models.CharField(blank=True, max_length=10, null=True)),
                ('route_description', models.TextField(blank=True, null=True)),
                ('hazards', models.TextField(blank=True, null=True)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalGpsTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_path', models.TextField()),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perevaladded')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField()),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perevaladded')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_name', models.CharField(max_length=255)),
                ('related_type', models.CharField(choices=[('mountain', 'Mountain'), ('ridge', 'Ridge'), ('other', 'Other')], max_length=50)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perevaladded')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perevaladded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_date', models.DateTimeField(auto_now_add=True)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perevaladded')),
            ],
        ),
    ]
