# Generated by Django 5.1.6 on 2025-04-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultylevel',
            name='characteristics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='difficultylevel',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.perevaluser')),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherInfo',
        ),
    ]
