# Generated by Django 5.1.6 on 2025-02-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevalhistory',
            name='pereval',
        ),
        migrations.RemoveField(
            model_name='perevalhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relatedobjects',
            name='pereval',
        ),
        migrations.DeleteModel(
            name='PerevalGpsTracks',
        ),
        migrations.DeleteModel(
            name='PerevalHistory',
        ),
        migrations.DeleteModel(
            name='RelatedObjects',
        ),
    ]
