# Generated by Django 5.1.6 on 2025-02-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_perevalhistory_pereval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaladded',
            name='level_autumn',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='level_spring',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='level_summer',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='level_winter',
        ),
        migrations.CreateModel(
            name='PerevalDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето'), ('autumn', 'Осень'), ('spring', 'Весна')], max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='main.perevaladded')),
            ],
            options={
                'unique_together': {('pereval', 'season')},
            },
        ),
    ]
