# Generated by Django 5.1.6 on 2025-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_difficultylevel_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='route_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
