# Generated by Django 5.1.6 on 2025-02-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_perevaladded_level_autumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='pereval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.perevaladded'),
        ),
    ]
