# Generated by Django 5.1.6 on 2025-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_perevalimages_pereval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevalimages',
            name='image_path',
        ),
        migrations.AddField(
            model_name='perevalimages',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='perevalimages',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
