# Generated by Django 5.1.6 on 2025-02-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_perevalimages_image_path_perevalimages_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perevaldifficulty',
            name='level',
        ),
        migrations.AddField(
            model_name='perevaldifficulty',
            name='difficulty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='perevaldifficulty',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.season'),
        ),
    ]
